//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Faculty_Announcement {
    protected global::System.Web.UI.ScriptManager ScriptManager1;
    protected global::System.Web.UI.WebControls.DropDownList drpCollage;
    protected global::System.Web.UI.WebControls.Panel pnlCourse;
    protected global::System.Web.UI.WebControls.CheckBoxList drpCourse;
    protected global::System.Web.UI.WebControls.DropDownList drpSemester;
    protected global::System.Web.UI.WebControls.TextBox txtTitle;
    protected global::System.Web.UI.WebControls.TextBox txtDescription;
    protected global::System.Web.UI.WebControls.TextBox txtDate;
    protected global::System.Web.UI.WebControls.FileUpload fuAttachment;
    protected global::System.Web.UI.WebControls.HiddenField hfAnnouncementID;
    protected global::System.Web.UI.WebControls.Button btnSave;
    protected global::System.Web.UI.WebControls.Button btnUpdate;
    protected global::System.Web.UI.WebControls.GridView gvAnnouncement;
    protected global::System.Web.UI.WebControls.ValidationSummary vsAnn;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCollage;
    protected global::System.Web.UI.WebControls.CustomValidator cvCourse;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSemester;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTitle;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDescription;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDate;
    protected global::System.Web.UI.WebControls.CustomValidator cvDate;
}
